name: Run Robot Framework Tests

on:
  push:
    branches: [ master ]  # or 'main' if that's your branch name
  schedule:
    # This cron expression runs the test every day at 2:00 AM UTC
    - cron: '0 4 * * *'

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install robotframework
        pip install robotframework-seleniumlibrary

    - name: Run Robot Framework tests
      run: |
        robot tests/

    - name: Upload Robot Framework logs
      uses: actions/upload-artifact@v4
      with:
        name: robot-logs
        path: |
          log.html
          report.html
          output.xml
