# .github/workflows/robot-framework.yml
name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework robotframework-seleniumlibrary

      - name: Install Firefox, Geckodriver, and Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox firefox-geckodriver xvfb

      - name: Run Robot Framework tests
        run: |
          xvfb-run -a robot --outputdir results tests/

      - name: Upload Robot Framework results
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/
